### ISSUE TITLE
cannot connect from outside if port is redirected via portmapping - Also ALWAYS an error when checing ports thorugh the admin

### ISSUE THREAD

**Issue by neil969** [RaspSDR/server#20]
I have a (long standing) OpenWebRX+ running on port 8073, so I can't port forward from outside my network from 8073 to the WEB-888.
This should be no problem as my router allows from internal & external ports ( as it shows in the help pages fro the WEB-888
I have the web-888 set up as the screenshot below:   
![image](https://github.com/user-attachments/assets/00493afa-64f8-4a65-88a4-c2e0dfb83c24)

and the Asus Routers port forwarding like this 
![image](https://github.com/user-attachments/assets/0b6e2186-9328-4d8f-b3b3-fca6ef71b0fb)

Expected result:- http://[external_IP]:8070 should connect to the WEB-888
Actual result: - Firefox can’t establish a connection to the server at [external_IP]:8070.
- Note that the port forwarding works fine if I point 8073 to it instead of the different external port.

Has anyone made this work? 
Why do I see an error rather than "yes" or "no" in the admin screen - which does not go away even when I know I can connect from the outside during my testing.
Thanks :)

**Comment by micked99** [comment]
It works for  me, you cant use the same internal port on the lan, change the port nr under the Network tab in Admin for example 8070 in the 888.
Use 8073:8070 in external port setting in the router and it will forward you to the correct SDR on your network.

I also see the same error when clicking "Check port open"

/Mikael

**Comment by howard0su** [comment]
Check port open is fixed. please verify.

**Comment by micked99** [comment]
Guess we need to wait for a new fw uppdate, its still on v2024.1008 when looking for Alpha uppdate

**Comment by howard0su** [comment]
updated, please test again.

**Comment by micked99** [comment]
I tried 1028/1029 (same?) problem is still there for both my direct ip and ddns ip, also noticed when clicking "Auto add NAT rule on firewall / router?" in 888 network tab it says "no device found" 

Just to verify it wasnt my mesh system acting up (Asus ai-mesh with 2 nodes) I connected the radio to the main router with a cable but it still gave the same errors.

/Mikael

**Comment by jurajbujdoso** [comment]
I am not sure if it help, but you can try to keep using 8073, but add additional proxy to 9073.

Then create an rule on asus for TCP traffic and destination port 9073.
Maybe I would also try to add    0.0.0.0  as   source IP for that rule.   

on web-888: 
```
apk add socat
socat TCP-LISTEN:9073,fork TCP:127.0.0.1:8073 &
```

I hope it allow you to use web interface http://externalIP:9073/ and http://internalIP:9073/. 
PS:  /admin will not work  (device ip and localhost are on different network). 

[openwebrx 9073 9073 tcp IPinternalDevice TCP 0.0.0.0  ]

Let me know it help or not.

Juraj
